### ISSUE TITLE
varnish hostname needs to be set dynamically

### ISSUE THREAD

**Issue by coledave** [inviqa/harness-base-php#332]
when deploying to a cluster with a resourcePrefix set the hostname for varnish will change accordingly, eg. `varnish-0.varnish-headless` might become `magento-varnish-0.magento-varnish-headless`.

currently this will stop magento from being able to purge cache entries.

**Comment by kierenevans** [comment]
Hopefully fixed in https://github.com/inviqa/harness-base-php/pull/333
