### ISSUE TITLE
[k8s] Elasticsearch does not boot with persistent storage enabled

### ISSUE THREAD

**Issue by kierenevans** [inviqa/harness-base-php#441]
Fatal error encountered in logs:
```
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
```

This is due to the persistent storage directory being owned by root when created, so we need an initContainer to chown the empty folder like we do with webapp.

**Comment by andytson-inviqa** [comment]
there is fsGroup that makes volumes attached with the specified group id, though it apparently doesn't work for NFS volumes

**Comment by kierenevans** [comment]
The case we are seeing is a block storage. I wondered why mysql didn't have an initContainer! Will check what it's doing. Thanks!

**Comment by kierenevans** [comment]
Ah it does `/docker-entrypoint.sh: find "$DATADIR" \! -user mysql -exec chown mysql '{}' +` in the mysql image as root

**Comment by andytson-inviqa** [comment]
I'm going to be using fsGroup on a project for another reason (can't chown k8s secret files), and it doesn't require an entrypoint or init container
