### ISSUE TITLE
www-data should not own every file

### ISSUE THREAD

**Issue by kierenevans** [inviqa/harness-base-php#57]
For static builds we are copying from the console image and chowning to www-data:www-data in https://github.com/inviqa/harness-base-php/blob/0.2.x/src/_base/docker/image/php-fpm/Dockerfile.twig#L10-L11

This means that the application can overwrite any file in it's codebase and provide a route for attackers who compromise a framework to inject into any file.

We should copy files in for static files as root:root and fix permissions to www-data:www-data for certain directories/files that the individual frameworks need to be able to modify for daily running.

Examples of the framework specific files/folders can be found in https://github.com/continuouspipe/dockerfiles/search?q=chown+APP_USER&unscoped_q=chown+APP_USER and https://github.com/continuouspipe/dockerfiles/search?q=chown+APP_GROUP&unscoped_q=chown+APP_GROUP

**Comment by marcomc** [comment]
I have made a PR ready for review. I have tested with Drupal8, Magento2 and Magento1
https://github.com/inviqa/harness-base-php/pull/96

**Comment by kierenevans** [comment]
https://github.com/inviqa/harness-base-php/pull/96 is in harnesses v0.2.6 :)
