### ISSUE TITLE
Add a "poweroff" command.

### ISSUE THREAD

**Issue by thomaslobjoie** [inviqa/harness-base-php#574]
When switching from a Workspace local environment to a Lando one, very often we need to manually turn off the proxy container. It would be a great addition to have the following command `ws poweroff` that would make sure that all workspace related containers are stopped.

**Comment by kierenevans** [comment]
Discussed this in a call.

This command is likely to be added to https://github.com/my127/workspace as it's a global command, with the intention of stopping all project containers, any mutagen sync's as well as all global workspace containers.

We will definitely need some way to track that a docker container is created by workspace. An easy way might be with docker container labels.

Perhaps we can inspect containers in the `my127ws` docker network, and get the `com.docker.compose.project.working_dir` label from those containers, and then call `ws disable` for each of those?

**Comment by kierenevans** [comment]
PR https://github.com/my127/workspace/pull/82 adds a `poweroff` command that looks up docker-compose projects with containers in the shared 'my127ws' network, and calls either `ws disable` or `docker-compose -p <composeProjectName> stop` on them
