### ISSUE TITLE
add elasticsearch to the list of available services

### ISSUE THREAD

**Issue by coledave** [inviqa/harness-base-php#59]
some of our stacks make use of elasticsearch, this work is to make the service available as part of the optional list of services within docker-compose.

**AC**
- [ ] elasticearch can be added to the "app.services" attribute
- [ ] attribute "elasticsearch.version" dictates which version of the image to use
- [ ] uses an official image such as https://hub.docker.com/_/elasticsearch

**Comment by kierenevans** [comment]
Note: lots of different versions needed - would be good to have this configurable.

**Comment by kierenevans** [comment]
This was added in https://github.com/inviqa/harness-base-php/pull/127 and was released in v0.2.7 of the harnesses :)
