### ISSUE TITLE
Release the _base harness so new frameworks can be prototyped prior to conversion to a harness

### ISSUE THREAD

**Issue by andytson-inviqa** [inviqa/harness-base-php#93]
Currently to prototype a new harness, it's required to copy the _base into tools/workspace/ and use the empty harness.

This leads to less clear separation of the base, and finding where it may not work in its current state.

If instead of the empty harness, it was possible to start from the base harness, then this will be easier to do.

**Comment by coledave** [comment]
The base is now available within (https://github.com/inviqa/harness-php) as :

> inviqa/php

Versioning is the same so the first available tag is `inviqa/php:v0.2.5`
